name: C/C++ Release candidate ubuntu

on:
  push:
    branches:
      - rc

jobs:
  build:

    runs-on: ubuntu-22.04

    env:
      EXEC_NAME: "${{ github.event.repository.name }}"

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'rc'

    - name: update apt cache & install packages
      run: sudo apt update && sudo apt -y install git cmake libgtk-3-dev libglew-dev libudev-dev libdbus-1-dev gettext libssl-dev libcurl4-openssl-dev

    - name: update submodule profiles
      working-directory: ./resources/profiles
      run: git submodule update --init

    - name: update clock
      run: sudo hwclock -s

    - name: change date in version
      run: sed -i "s/+UNKNOWN/_$(date '+%F')/" version.inc

    - name: build deps & slicer
      run: ./BuildLinux.sh -ds

    - name: make .pot
      working-directory: ./build
      run: make gettext_make_pot

    - name: build tar & appimage
      working-directory: ./build
      run: src/BuildLinuxImage.sh -i

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: rc_linux.tar
        path: build/${{ github.event.repository.name }}.tar

    - name: Upload appimage
      uses: actions/upload-artifact@v3
      with:
        name: rc-${{ github.event.repository.name }}.AppImage
        path: build/${{ github.event.repository.name }}_ubu64.AppImage
