name: C/C++ Release candidate arm macos

on:
  push:
    branches:
      - rc

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'rc'
    - name: build deps & slicer
      run: ./BuildMacOS.sh -ia
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: rc_arm_macos.tar
        path: build/${{ github.event.repository.name }}.tar
